/* ==========================================================================
   L'Armoire à Cuillères — la traduction anglaise (chargée seulement en anglais, par le script de <head>)
   La clé : le texte français tel qu'il est écrit (espaces réduits) ; la valeur : l'anglais. {nom} : une valeur.
   Les clés : node tools/i18n.mjs (--ecrire ajoute celles qui manquent, --verifier contrôle).
   ========================================================================== */
window.AC_EN = {
  "L'Armoire à Cuillères · Bar à chocolat & salon de thé à Clermont-Ferrand": "L'Armoire à Cuillères · Hot chocolate bar & tea room in Clermont-Ferrand",
  "Bar à chocolat et salon de thé rue des Chaussetiers à Clermont-Ferrand : 12 chocolats chauds grands crus, pâtisseries faites maison, thés, cafés et brunch du dimanche à 23 €. Ouvert du mardi au dimanche.": "Hot chocolate bar and tea room on rue des Chaussetiers in Clermont-Ferrand: 12 grand cru hot chocolates, homemade pastries, teas, coffees and Sunday brunch at €23. Open Tuesday to Sunday.",
  "Bar à chocolat<br>&amp; salon de thé": "Hot chocolate bar<br>&amp; tea room",
  "Encore mieux<br>sur votre téléphone": "Even better<br>on your phone",
  "<em>dans la</em> formule": "<em>what’s</em> included",
  "buffet <em>à volonté</em>": "<em>all-you-can-eat</em> buffet",
  "Après quelques années dans les pays froids, en Pologne puis au Canada, Mallo est rentrée dans sa ville natale avec une idée en tête : un petit cocon pour les jours gris, chaud l’hiver, frais l’été, <em>douillet comme un duvet d’oiseau</em>.": "After a few years in cold countries, first Poland and then Canada, Mallo came back to her home town with one idea in mind: a little cocoon for grey days, warm in winter, cool in summer, <em>as snug as a bird’s down</em>.",
  "Ce qui revient le plus : <strong>le chocolat chaud</strong>, <strong>le brunch</strong> et <strong>le cheesecake</strong>.": "What comes up most: <strong>the hot chocolate</strong>, <strong>the brunch</strong> and <strong>the cheesecake</strong>.",
  "QR code de l’appli": "QR code for the app",
  "L'Armoire à Cuillères": "L'Armoire à Cuillères",
  "Langue : français": "Language: French",
  "Revenir dans la rue": "Back to the street",
  "Accès rapides": "Quick links",
  "Choisir un chocolat grand cru": "Choose a grand cru hot chocolate",
  "Rubriques de la carte": "Menu sections",
  "Une tablée de brunch pour deux, vue de dessus : pour chacun une part de tarte rustique et sa salade composée, une boisson chaude, un jus de pomme et un cookie ; au milieu, le buffet : pain, beurre, confitures, miel, fromage blanc, muesli, pâte à tartiner, fruits frais et petites gourmandises": "A brunch table for two, seen from above: for each person, a slice of rustic tart with a mixed salad, a hot drink, an apple juice and a cookie; in the middle, the buffet: bread, butter, jams, honey, fromage blanc, muesli, spread, fresh fruit and little treats",
  "Une personne de moins": "One fewer person",
  "Une personne de plus": "One more person",
  "Une sélection d’avis": "A selection of reviews",
  "Navigation": "Navigation",
  "Fermer": "Close",
  "Julie": "Emma",
  "Végétarien, un anniversaire, une poussette…": "Vegetarian, a birthday, a pushchair…",
  "Une bougie, un « Joyeux anniversaire Léa »…": "A candle, “Happy birthday Lily”…",
  "L’Armoire à Cuillères, l’appli : cliquez, tout marche": "L’Armoire à Cuillères, the app: click around, everything works",
  "Issu de l’agriculture biologique": "From organic farming",
  "Boisson glacée": "Iced drink",
  "Aller au contenu": "Skip to content",
  "L’Armoire à Cuillères": "L’Armoire à Cuillères",
  "Bar à chocolat & salon de thé à": "Hot chocolate bar & tea room in",
  "Clermont-Ferrand": "Clermont-Ferrand",
  "Douze chocolats chauds grands crus, des pâtisseries faites maison chaque matin, des thés, des cafés et le brunch du dimanche, dans une toute petite armoire de la rue des Chaussetiers.": "Twelve grand cru hot chocolates, homemade pastries every morning, teas, coffees and Sunday brunch, in a tiny little armoire on rue des Chaussetiers.",
  "11 rue des Chaussetiers": "11 rue des Chaussetiers",
  "Du mardi au samedi · 13h – 19h": "Tuesday to Saturday · 1pm – 7pm",
  "Brunch le dimanche · dès 11h30": "Sunday brunch · from 11:30am",
  "Scannez : l’appli s’ouvre sur votre téléphone.": "Scan the code: the app opens on your phone.",
  "À ajouter à l’écran d’accueil, comme une vraie appli. Ici, dans le téléphone, tout marche : touchez, écoutez, goûtez.": "Add it to your home screen, just like a real app. Here, in the phone, everything works: tap, listen, taste.",
  "Bar à chocolat · Clermont-Ferrand": "Hot chocolate bar · Clermont-Ferrand",
  "Entrer": "Come in",
  "Entrer sans le son": "Come in without sound",
  "FR": "FR",
  "Français": "Français",
  "EN": "EN",
  "English": "English",
  "Touchez la porte, les nichoirs, l’ardoise…": "Tap the door, the birdhouses, the chalkboard…",
  "Douze chocolats chauds grands crus, des pâtisseries faites maison chaque matin, des thés, des cafés et le brunch du dimanche. Dans une toute petite boutique de la rue des Chaussetiers, à deux pas de la cathédrale.": "Twelve grand cru hot chocolates, homemade pastries every morning, teas, coffees and Sunday brunch. In a tiny little shop on rue des Chaussetiers, a stone’s throw from the cathedral.",
  "Itinéraire": "Directions",
  "Appeler": "Call",
  "Brunch": "Brunch",
  "Instagram": "Instagram",
  "Ouvert aujourd’hui": "Open today",
  "Les horaires": "Opening hours",
  "Pâtisseries du jour": "Today’s pastries",
  "Fondant lait caramélisé": "Caramel milk fondant",
  "Fondant noir pointe de sel": "Salted dark fondant",
  "Brownie noix, noisettes": "Walnut hazelnut brownie",
  "Cheesecake citron vert": "Lime cheesecake",
  "Cookies pépites de chocolat": "Chocolate chip cookies",
  "Cake marbré chocolat": "Chocolate marble cake",
  "Tarte citron meringuée": "Lemon meringue tart",
  "Fait-maison par Mallo, Amina": "Homemade by Mallo & Amina",
  "La carte": "Menu",
  "Chocolats chauds, pâtisseries maison, thés & cafés": "Hot chocolates, homemade pastries, teas & coffees",
  "Chocolats grands crus": "Grand cru hot chocolates",
  "Du plus doux au plus intense : choisissez votre cru, on vous le sert.": "From mildest to most intense: choose your cru and we’ll pour it for you.",
  "Les douze crus": "The twelve crus",
  "Blanc Ivoire 33 %": "Blanc Ivoire 33%",
  "Chocolat blanc peu sucré, aux notes de gâteau au beurre & de vanille.": "Lightly sweetened white chocolate, with notes of butter cake & vanilla.",
  "Kewane 34 %": "Kewane 34%",
  "Crémeux & réglissé.": "Creamy, with a hint of liquorice.",
  "Caramélia 35 %": "Caramélia 35%",
  "Douceur sucrée & ronde.": "Sweet & rounded.",
  "Elianza Lait 35 %": "Elianza Lait 35%",
  "Crème glacée, caramel au beurre, cacao grillé & miel de châtaignier.": "Ice cream, butter caramel, roasted cocoa & chestnut honey.",
  "Vanuari Lait 39 %": "Vanuari Lait 39%",
  "Lait entier aux notes sucrées.": "Whole milk with sweet notes.",
  "Z-Caramel 43 %": "Z-Caramel 43%",
  "Texture craquante de caramel.": "Crunchy caramel texture.",
  "Elianza Noir 55 %": "Elianza Noir 55%",
  "Cacao grillé, réglisse, anis étoilé & vanille.": "Roasted cocoa, liquorice, star anise & vanilla.",
  "Vanuari Noir 63 %": "Vanuari Noir 63%",
  "Texture fluide et équilibrée, douceur du miel, fruits rouges & poivre.": "Smooth, balanced texture, honeyed sweetness, red berries & pepper.",
  "Z-Café 70 %": "Z-Café 70%",
  "Véritables grains de café broyés avec le cacao.": "Real coffee beans ground with the cocoa.",
  "Mokaya Noir 75 %": "Mokaya Noir 75%",
  "BIO": "ORGANIC",
  "Fruits exotiques, miel, amandes & noisettes grillées, cacao fin grillé et poivré, vanille.": "Exotic fruit, honey, roasted almonds & hazelnuts, fine roasted, peppery cocoa, vanilla.",
  "Arcango Noir 85 %": "Arcango Noir 85%",
  "Cacao grillé aux légères notes de châtaignes.": "Roasted cocoa with light notes of chestnut.",
  "Noir Infini 99 %": "Noir Infini 99%",
  "La saveur la plus intense.": "The most intense flavour.",
  "Les classiques": "The classics",
  "Chocolat Soyeux": "Silky hot chocolate",
  "Doux & non sucré.": "Mild & unsweetened.",
  "Chocolat Intense": "Intense hot chocolate",
  "Épais & corsé, cannelle et miel.": "Thick & full-bodied, with cinnamon and honey.",
  "Chocolats gourmets": "Gourmet hot chocolates",
  "Praliné noisette": "Hazelnut praline",
  "Guimauve": "Marshmallow",
  "Coco façon Bounty": "Coconut, Bounty-style",
  "Chocolats glacés": "Iced chocolates",
  "Chocolat frappé simple": "Classic chocolate frappé",
  "Mocha glacé": "Iced mocha",
  "Cafés": "Coffee",
  "Espresso": "Espresso",
  "Lungo": "Lungo",
  "Cappuccino": "Cappuccino",
  "Café latte": "Latte",
  "Café viennois": "Viennese coffee",
  "Mocha": "Mocha",
  "Espresso, chocolat & lait.": "Espresso, chocolate & milk.",
  "Spécialités": "Specialities",
  "Chaï Latte": "Chai latte",
  "Latte aux épices.": "Spiced latte.",
  "Matcha Latte": "Matcha latte",
  "Matcha Fraise": "Strawberry matcha",
  "Thés & infusions": "Teas & infusions",
  "Montagne Bleue": "Montagne Bleue",
  "Thé noir, fraise & rhubarbe.": "Black tea, strawberry & rhubarb.",
  "Blue of London": "Blue of London",
  "Thé noir du Yunnan & bergamote.": "Yunnan black tea & bergamot.",
  "Thé des Alizés": "Thé des Alizés",
  "Thé vert, pêche blanche & fleur d’oranger.": "Green tea, white peach & orange blossom.",
  "Thé des Fakirs": "Thé des Fakirs",
  "Thé vert, cardamome, gingembre & agrumes.": "Green tea, cardamom, ginger & citrus.",
  "Thé Merveilleux": "Thé Merveilleux",
  "Thé vert, amandes caramélisées & pistache.": "Green tea, caramelised almonds & pistachio.",
  "Limoncha": "Limoncha",
  "Thé vert & noir aux influences japonaises, riz grillé, amandes & citron.": "Green & black tea with a Japanese touch, toasted rice, almonds & lemon.",
  "Mama Relax": "Mama Relax",
  "Infusion BIO, mélisse & lavande.": "Organic infusion, lemon balm & lavender.",
  "L’Herboriste": "L’Herboriste",
  "Infusion BIO, curcuma, réglisse & verveine.": "Organic infusion, turmeric, liquorice & verbena.",
  "Paris for You": "Paris for You",
  "Thé vert, litchi, framboise & notes de rose.": "Green tea, lychee, raspberry & notes of rose.",
  "Louvre côté Jardin": "Louvre côté Jardin",
  "Thé vert, pomme, prune & coing.": "Green tea, apple, plum & quince.",
  "Boissons fraîches": "Cold drinks",
  "Matcha glacé": "Iced matcha",
  "Sodas": "Soft drinks",
  "Coca-Cola, Coca-Cola Zéro, ou limonade Lorina.": "Coca-Cola, Coca-Cola Zero or Lorina lemonade.",
  "Jus de fruits": "Fruit juice",
  "Citronnade maison": "Homemade lemonade",
  "Thé glacé maison": "Homemade iced tea",
  "Pêche, sureau, framboise ou citron.": "Peach, elderflower, raspberry or lemon.",
  "Sirop à l’eau": "Cordial with water",
  "Gâteaux": "Cakes",
  "Gâteaux du jour : voir sur l’ardoise": "Today’s cakes: see the chalkboard",
  "Fondant chocolat noir": "Dark chocolate fondant",
  "Pointe de sel.": "A hint of salt.",
  "Fondant chocolat au lait": "Milk chocolate fondant",
  "Brownie": "Brownie",
  "Cheesecake": "Cheesecake",
  "Cookie": "Cookie",
  "Cake": "Loaf cake",
  "Pour les petits bidons": "For little tummies",
  "Formule enfant": "Kids’ menu",
  "Verre de lait spéculoos-vanille, chocolat chaud ou boisson fraîche + petite part de gâteau.": "A glass of speculoos-vanilla milk, a hot chocolate or a cold drink + a small slice of cake.",
  "Suppléments": "Extras",
  "Arôme": "Flavour",
  "Vanille, caramel, spéculoos ou praliné noisette.": "Vanilla, caramel, speculoos or hazelnut praline.",
  "Lait végétal": "Plant-based milk",
  "Avoine, coco ou amande.": "Oat, coconut or almond.",
  "Chantilly": "Whipped cream",
  "Tout est fait maison, chaque jour, dans notre petit labo. Le chocolat chaud est servi autour de 65 °C : jamais bouillant, pour garder ses arômes.": "Everything is homemade, every day, in our little kitchen. The hot chocolate is served at around 65°C: never scalding, so it keeps all its aromas.",
  "chaque dimanche": "every Sunday",
  "Le brunch": "Brunch",
  "dès 11h30": "from 11:30am",
  "Un exemple de tablée : le plat salé change chaque dimanche. Touchez un plat, il se présente.": "An example table: the savoury dish changes every Sunday. Tap a dish and it introduces itself.",
  "Un plat salé au choix": "A savoury dish of your choice",
  "accompagné de sa salade fraîche": "served with a fresh salad",
  "Une boisson chaude au choix": "A hot drink of your choice",
  "café, thé ou chocolat chaud": "coffee, tea or hot chocolate",
  "Un jus de pomme": "An apple juice",
  "Notre délicieux cookie": "Our delicious cookie",
  "la petite touche sucrée signée L’Armoire": "L’Armoire’s signature sweet touch",
  "Et surtout… un buffet pour composer votre brunch comme vous l’aimez.": "And above all… a buffet to build your brunch just the way you like it.",
  "Beurre": "Butter",
  "Confitures": "Jams",
  "Miel": "Honey",
  "Fromage blanc": "Fromage blanc",
  "Muesli": "Muesli",
  "Pâtes à tartiner": "Spreads",
  "Pain": "Bread",
  "Fruits frais": "Fresh fruit",
  "Petites gourmandises…": "Little treats…",
  "Réserver": "Book",
  "Les places sont limitées : la réservation se fait par téléphone ou par SMS. Préparez votre message ici, il partira de votre téléphone.": "Places are limited: booking is by phone or text. Write your message here and it will be sent from your phone.",
  "Quel dimanche ?": "Which Sunday?",
  "Vers quelle heure ?": "Around what time?",
  "Nombre de personnes": "Number of people",
  "Votre prénom": "Your first name",
  "Un petit mot": "A little note",
  "(facultatif)": "(optional)",
  "Plus de 6 personnes ?": "More than 6 people?",
  "On s’organise ensemble au téléphone : appelez-nous pour réserver.": "We’ll sort it out together over the phone: call us to book.",
  "Envoyer par SMS": "Send by text",
  "L’équipe vous répond pour confirmer. Le brunch se prend sur place, le dimanche.": "The team will reply to confirm. Brunch is eat-in only, on Sundays.",
  "Ma carte fidélité": "My loyalty card",
  "À chaque passage, on accroche une cuillère.": "With every visit, we hang up a spoon.",
  "À la dixième, votre chocolat grand cru est offert.": "On the tenth, your grand cru hot chocolate is on us.",
  "Comment ça marche ?": "How does it work?",
  "Au comptoir, montrez votre carte : l’équipe y accroche une cuillère pour chaque boisson, avec son code. Dix cuillères, et le chocolat suivant est pour nous. Votre compte tient à votre numéro de téléphone : vous retrouvez votre carte même sur un autre téléphone. Pas d’e-mail, pas de publicité.": "At the counter, show your card: the team hangs a spoon on it for each drink, using their code. Ten spoons, and the next hot chocolate is on us. Your account is tied to your phone number, so you’ll find your card again even on another phone. No emails, no adverts.",
  "Nous": "About",
  "Une toute petite Armoire, pleine de chocolat, de gâteaux et de livres": "A tiny little Armoire, full of chocolate, cakes and books",
  "Mallo": "Mallo",
  "Ici, on poche, on crème, on dresse, on blanchit, on saupoudre, on fouette, on glace, on zeste, on enfourne, on émulsionne, on nappe, on caramélise, on chérit notre matière première : notre miel de caractère, notre farine soyeuse, notre crème onctueuse, nos œufs dorés et notre chocolat sélectionné. Et donc, ici on aime le fait maison.": "Here, we pipe, we cream, we garnish, we whisk, we dust, we whip, we glaze, we zest, we bake, we emulsify, we coat, we caramelise, we cherish our ingredients: our full-flavoured honey, our silky flour, our velvety cream, our golden eggs and our hand-picked chocolate. And so, here we love all things homemade.",
  "Ici,": "Here,",
  "on poche,": "we pipe,",
  "on crème,": "we cream,",
  "on dresse,": "we garnish,",
  "on blanchit,": "we whisk,",
  "on saupoudre,": "we dust,",
  "on fouette,": "we whip,",
  "on glace,": "we glaze,",
  "on zeste,": "we zest,",
  "on enfourne,": "we bake,",
  "on émulsionne,": "we emulsify,",
  "on nappe,": "we coat,",
  "on caramélise,": "we caramelise,",
  "on chérit notre matière première :": "we cherish our ingredients:",
  "notre miel de caractère,": "our full-flavoured honey,",
  "notre farine soyeuse,": "our silky flour,",
  "notre crème onctueuse,": "our velvety cream,",
  "nos œufs dorés": "our golden eggs",
  "et notre chocolat sélectionné.": "and our hand-picked chocolate.",
  "Et donc, ici on aime le fait maison.": "And so, here we love all things homemade.",
  "Revoir Mallo": "Watch Mallo again",
  "L’histoire": "Our story",
  "Mallo, les pays froids, et un cocon pour les jours gris": "Mallo, cold countries and a cocoon for grey days",
  "Ce sera une toute petite boutique dans une ruelle du vieux Clermont : du bois, des tables massives sous des tasses fines, de la vaisselle chinée, des livres en haut de l’armoire, des goûters généreux « comme chez mamie »… et du chocolat, beaucoup de chocolat.": "It would be a tiny shop in a little lane of old Clermont: wood, solid tables beneath delicate cups, flea-market crockery, books on top of the armoire, generous teatime treats “just like at Granny’s”… and chocolate, lots of chocolate.",
  "Aujourd’hui, Mallo et Amina pâtissent chaque matin dans le labo de la rue des Chaussetiers. Tout est fait maison.": "Today, Mallo and Amina bake every morning in the kitchen on rue des Chaussetiers. Everything is homemade.",
  "Nos producteurs": "Our producers",
  "Du lait bio au miel : sept producteurs d’Auvergne": "From organic milk to honey: seven Auvergne producers",
  "La base, c’est une bonne matière première, achetée au plus près.": "It all starts with good ingredients, sourced as close to home as possible.",
  "Le lait bio des chocolats chauds": "Organic milk for the hot chocolates",
  "GAEC de Montjeudi · Olby": "GAEC de Montjeudi · Olby",
  "La farine": "Flour",
  "Moulin Gribory · Châtelus": "Moulin Gribory · Châtelus",
  "Le café": "Coffee",
  "Chazal, torréfacteur · Issoire": "Chazal, coffee roaster · Issoire",
  "Le pain des tartines": "Bread for the tartines",
  "Pain Paillasse · Clermont-Ferrand": "Pain Paillasse · Clermont-Ferrand",
  "Les fraises": "Strawberries",
  "Le Verger d’Ornon · Lezoux": "Le Verger d’Ornon · Lezoux",
  "Le miel et le confit de noisettes": "Honey and hazelnut confit",
  "Miellerie de Grattepaille · Saint-Préjet-Armandon": "Miellerie de Grattepaille · Saint-Préjet-Armandon",
  "Les tisanes bio": "Organic herbal teas",
  "Happy Plantes · Volvic": "Happy Plantes · Volvic",
  "Un gâteau entier ?": "A whole cake?",
  "Nos pâtisseries chez vous, sur commande": "Our pastries at your place, made to order",
  "Nos pâtisseries chez vous, pour un anniversaire ou un dimanche : commandez au moins 24 h à l’avance.": "Our pastries at your place, for a birthday or a Sunday treat: order at least 24 hours in advance.",
  "Préparer ma commande": "Start my order",
  "Sur Instagram": "On Instagram",
  "Ce qu’on en dit": "What people say",
  "602 avis sur Google": "602 reviews on Google",
  "Nous trouver": "Find us",
  "63000 Clermont-Ferrand": "63000 Clermont-Ferrand",
  "Dans le vieux Clermont, rue piétonne, à deux pas de la cathédrale.": "In old Clermont, on a pedestrian street, a stone’s throw from the cathedral.",
  "Horaires": "Opening hours",
  "Mardi": "Tuesday",
  "Mercredi": "Wednesday",
  "Jeudi": "Thursday",
  "Vendredi": "Friday",
  "Samedi": "Saturday",
  "Dimanche": "Sunday",
  "brunch dès 11h30": "brunch from 11:30am",
  "Lundi": "Monday",
  "Fermé": "Closed",
  "Questions fréquentes": "Frequently asked questions",
  "Peut-on réserver pour le goûter ?": "Can I book for tea and cake?",
  "Non : pour le goûter, on vient comme on est, sans réservation. L’Armoire est toute petite ; en semaine ou en début d’après-midi, on trouve plus facilement une place.": "No: for tea and cake, just come as you are, no booking needed. L’Armoire is tiny; on weekdays or early in the afternoon, you’ll find a seat more easily.",
  "Comment réserver le brunch du dimanche ?": "How do I book Sunday brunch?",
  "Par téléphone ou SMS au 07 83 41 21 45. Le brunch est servi tous les dimanches à partir de 11h30, 23 € par personne ; les places sont limitées.": "By phone or text on 07 83 41 21 45. Brunch is served every Sunday from 11:30am, €23 per person; places are limited.",
  "Le chocolat chaud est-il servi bouillant ?": "Is the hot chocolate served boiling hot?",
  "Non : il est préparé à la minute et servi autour de 65 °C, la température où l’on sent le mieux ses arômes.": "No: it’s made to order and served at around 65°C, the temperature at which its aromas come through best.",
  "Y a-t-il des laits végétaux ?": "Do you have plant-based milks?",
  "Oui : avoine, coco ou amande, pour 0,50 € de plus. Arômes (vanille, caramel, spéculoos, praliné noisette) : 0,30 €.": "Yes: oat, coconut or almond, for €0.50 extra. Flavours (vanilla, caramel, speculoos, hazelnut praline): €0.30.",
  "Peut-on commander un gâteau entier ?": "Can I order a whole cake?",
  "Oui, au moins 24 h à l’avance, par e-mail à hello@larmoireacuilleres.com.": "Yes, at least 24 hours in advance, by email to hello@larmoireacuilleres.com.",
  "Tout est-il fait maison ?": "Is everything homemade?",
  "Oui : les pâtisseries sont préparées chaque jour dans notre labo, rue des Chaussetiers, avec du lait bio, du miel et de la farine de producteurs d’Auvergne.": "Yes: our pastries are made every day in our kitchen on rue des Chaussetiers, with organic milk, honey and flour from Auvergne producers.",
  "Les petits bruits de la boutique": "The little sounds of the shop",
  "· bar à chocolat · depuis 2013": "· hot chocolate bar · since 2013",
  "Photos Instagram : L’Armoire à Cuillères et @agenceares.": "Instagram photos: L’Armoire à Cuillères and @agenceares.",
  "Mentions légales": "Legal notice",
  "Accueil": "Home",
  "Fidélité": "Loyalty",
  "Commander un gâteau": "Order a cake",
  "Au moins 24 h à l’avance, à retirer à la boutique. L’équipe vous répond avec le prix et l’heure de retrait.": "At least 24 hours in advance, for collection at the shop. The team will reply with the price and collection time.",
  "Quel gâteau ?": "Which cake?",
  "Pour combien ?": "For how many?",
  "6 parts": "6 slices",
  "8 parts": "8 slices",
  "10 parts": "10 slices",
  "12 parts": "12 slices",
  "Pour quel jour ?": "For which day?",
  "Votre téléphone": "Your phone",
  "(pour vous rappeler)": "(so we can call you back)",
  "Un mot": "A note",
  "Envoyer par e-mail": "Send by email",
  "Bar à chocolat · pâtisseries maison · brunch du dimanche": "Hot chocolate bar · homemade pastries · Sunday brunch",
  "dans le vieux Clermont, à deux pas de la cathédrale": "in old Clermont, a stone’s throw from the cathedral",
  "Thé vert, pêche blanche & fleur d'oranger.": "Green tea, white peach & orange blossom.",
  "L'Herboriste": "L’Herboriste",
  "Sirop à l'eau": "Cordial with water",
  "Gâteaux du jour : voir sur l'ardoise": "Today’s cakes: see the chalkboard",
  "Et surtout… un buffet à volonté pour composer votre brunch comme vous l’aimez.": "And above all… an all-you-can-eat buffet to build your brunch just the way you like it.",
  "Réservation au 07 83 41 21 45 : les places sont limitées, pensez à réserver !": "Bookings on 07 83 41 21 45: places are limited, so do book ahead!",
  "Non : pour le goûter, on vient comme on est, sans réservation. L'Armoire est toute petite ; en semaine ou en début d'après-midi, on trouve plus facilement une place.": "No: for tea and cake, just come as you are, no booking needed. L’Armoire is tiny; on weekdays or early in the afternoon, you’ll find a seat more easily.",
  "Non : il est préparé à la minute et servi autour de 65 °C, la température où l'on sent le mieux ses arômes.": "No: it’s made to order and served at around 65°C, the temperature at which its aromas come through best.",
  "Oui, au moins 24 h à l'avance, par e-mail à hello@larmoireacuilleres.com.": "Yes, at least 24 hours in advance, by email to hello@larmoireacuilleres.com.",
  "Oui : les pâtisseries sont préparées chaque jour dans notre labo, rue des Chaussetiers, avec du lait bio, du miel et de la farine de producteurs d'Auvergne.": "Yes: our pastries are made every day in our kitchen on rue des Chaussetiers, with organic milk, honey and flour from Auvergne producers.",
  "Lait caramel ou noir pointe de sel ? Le dilemme du jour.": "Caramel milk or salted dark? Today’s dilemma.",
  "Pas besoin d'une occasion pour manger une pâtisserie. L'occasion, c'est toi.": "No need for an occasion to have a pastry. You’re the occasion.",
  "Un peu de nous, beaucoup de gourmandise.": "A little bit of us, a whole lot of sweetness.",
  "Une petite sélection de ce qui vous attend à L’Armoire à Cuillères.": "A little selection of what awaits you at L’Armoire à Cuillères.",
  "La terrasse, rue des Chaussetiers.": "The terrace, rue des Chaussetiers.",
  "Le choix le plus difficile de la journée…": "The hardest choice of the day…",
  "un chocolat chaud grand cru offert": "a free grand cru hot chocolate",
  "Prénom N.": "First N.",
  "Le chocolat chaud le plus onctueux de Clermont : on choisit son cru, il arrive fumant avec une part de fondant. Une adresse à garder.": "The creamiest hot chocolate in Clermont: you choose your cru, and it arrives steaming with a slice of fondant. A place to remember.",
  "Brunch du dimanche très généreux : la tarte salée et sa salade, le buffet à volonté, et le cookie pour finir. On a déjà réservé le prochain.": "A very generous Sunday brunch: the savoury tart and its salad, the all-you-can-eat buffet, and the cookie to finish. We’ve already booked the next one.",
  "Le cheesecake au citron vert est une merveille, léger et bien acidulé. Tout est fait maison, et ça se sent.": "The lime cheesecake is a marvel, light and nicely tangy. Everything is homemade, and you can tell.",
  "Un tout petit salon, chaleureux comme un cocon : de vieilles tasses, des livres, et une équipe aux petits soins.": "A tiny tea room, as cosy as a cocoon: old cups, books, and a team who really look after you.",
  "La salle se remplit vite le samedi, mieux vaut venir en début d’après-midi. Mais quelle carte de thés et de chocolats !": "It fills up fast on Saturdays, so it’s best to come early in the afternoon. But what a choice of teas and hot chocolates!",
  "Accueil adorable : on nous a fait goûter deux crus avant de choisir. Coup de cœur pour le Vanuari noir aux fruits rouges.": "Such a lovely welcome: they let us taste two crus before we chose. Fell in love with the Vanuari Noir and its red berries.",
  "Les pâtisseries changent chaque jour sur l’ardoise : brownie, tarte citron meringuée… Impossible de ne pas revenir.": "The pastries change every day on the chalkboard: brownie, lemon meringue tart… Impossible not to come back.",
  "Aujourd’hui": "Today",
  "Fermé aujourd’hui": "Closed today",
  "ouvre {quand}": "opens {quand}",
  ", brunch dès {h}": ", brunch from {h}",
  "fermé": "closed",
  ". Horaires : {semaine}.": ". Opening hours: {semaine}.",
  "Entrez, installez-vous !": "Come in and make yourself at home!",
  "C’est fermé pour l’instant… mais entrez voir le salon.": "We’re closed for now… but come in and see the tea room.",
  "Bonjour !": "Hello!",
  "Je voudrais commander : {gateau}.": "I’d like to order: {gateau}.",
  "Je voudrais commander : {gateau}, pour {parts} parts.": "I’d like to order: {gateau}, {parts} slices.",
  "Pour le {jour}, à retirer à la boutique.": "For collection at the shop on {jour}.",
  "Merci !": "Thank you!",
  "« {msg} »": "“{msg}”",
  "Commande de gâteau · {jour}": "Cake order · {jour}",
  "La boutique est fermée ce jour-là": "The shop is closed that day",
  "Dim.": "Sun.",
  ", au nom de {prenom}": ", under the name {prenom}",
  "Bonjour ! Je voudrais réserver le brunch du dimanche {date} à {heure}, pour {n} personnes{qui}.": "Hello! I’d like to book brunch on Sunday {date} at {heure}, for {n} people{qui}.",
  "Bonjour ! Je voudrais réserver le brunch du dimanche {date} à {heure}, pour {n} personne{qui}.": "Hello! I’d like to book brunch on Sunday {date} at {heure}, for {n} person{qui}.",
  "Pour un grand groupe, appelez-nous : on s’organise ensemble.": "For a large group, give us a call: we’ll sort it out together.",
  "Depuis votre téléphone : SMS au {tel}": "From your phone: text {tel}",
  "Fondant chocolat noir, pointe de sel": "Salted dark chocolate fondant",
  "Fondant chocolat au lait caramélisé": "Caramelised milk chocolate fondant",
  "Cookies (par 6)": "Cookies (box of 6)",
  "{n} %": "{n}%",
  "Sur la table : {nom}.": "On the table: {nom}.",
  "{n} % de cacao": "{n}% cocoa",
  "{nom}, de {a} à {b} %": "{nom}, from {a} to {b}%",
  "Crus plus doux": "Milder crus",
  "Crus plus intenses": "More intense crus",
  "Chocolats": "Chocolate",
  "Thés": "Tea",
  "Fraîches": "Cold drinks",
  "Enfants": "Kids",
  "Doux": "Mild",
  "Équilibrés": "Balanced",
  "Intenses": "Intense",
  "Ouvert · jusqu’à {h}": "Open · until {h}",
  "Ferme bientôt · {h}": "Closing soon · {h}",
  "à {h}": "at {h}",
  "demain à {h}": "tomorrow at {h}",
  "{jour} à {h}": "{jour} at {h}",
  "Fermé · ouvre {quand}": "Closed · opens {quand}",
  "La devanture de L'Armoire à Cuillères, rue des Chaussetiers": "The shopfront of L'Armoire à Cuillères, rue des Chaussetiers",
  "HORAIRES": "HOURS",
  "OUVERT": "OPEN",
  "PÂTISSERIES": "TODAY’S",
  "DU JOUR": "PASTRIES",
  "FERMÉ": "CLOSED",
  "Fermeture": "Closed",
  "Râtelier de {n} cuillères : {k} accrochées": "Spoon rack for {n} spoons: {k} hung up",
  "VOTRE PRÉNOM ICI": "YOUR NAME HERE",
  "VOTRE CHOCOLAT EST OFFERT": "YOUR HOT CHOCOLATE IS ON US",
  "{k} / {n} CUILLÈRES": "{k} / {n} SPOONS",
  "Créez votre compte": "Create your account",
  "Votre prénom se grave sur la plaque, et votre carte vous suit, même sur un autre téléphone.": "Your first name is engraved on the plaque, and your card goes with you, even to another phone.",
  "(sur la plaque)": "(on the plaque)",
  "Votre numéro de téléphone": "Your phone number",
  "Créer mon compte": "Create my account",
  "Votre numéro sert seulement à retrouver votre carte : jamais de publicité. Déjà un compte ? Le même numéro vous reconnecte.": "Your number is only used to find your card: never any adverts. Already have an account? The same number logs you back in.",
  "Graver mon prénom : créer mon compte": "Engrave my name: create my account",
  "Votre prénom, pour la plaque": "Your first name, for the plaque",
  "Ce numéro ne semble pas complet": "This number doesn’t look complete",
  "Bon retour {nom} ! Votre carte est là.": "Welcome back, {nom}! Here’s your card.",
  "Bienvenue {nom} ! Votre compte est créé, votre prénom est gravé.": "Welcome, {nom}! Your account is ready and your name is engraved.",
  "À montrer au comptoir si on vous le demande.": "Show this at the counter if asked.",
  "Se déconnecter": "Log out",
  "Mon chocolat offert : à valider au comptoir": "My free hot chocolate: redeem at the counter",
  "Accrocher une cuillère (au comptoir)": "Hang a spoon (at the counter)",
  "Mon QR code": "My QR code",
  "Se déconnecter ? Votre carte reste liée à votre numéro : il suffira de le saisir à nouveau.": "Log out? Your card stays linked to your number: just enter it again to get it back.",
  "Chocolat offert": "Free hot chocolate",
  "Accrocher des cuillères": "Hang up spoons",
  "L’équipe valide le chocolat offert avec son code.": "The team confirms your free hot chocolate with their code.",
  "Réservé à l’équipe : combien de boissons, puis le code.": "Team only: how many drinks, then the code.",
  "Une de moins": "One fewer",
  "Une de plus": "One more",
  "cuillère(s)": "spoon(s)",
  "Effacer": "Delete",
  "Trop d’essais : patientez une minute.": "Too many tries: please wait a minute.",
  "Code incorrect. Réessayez dans une minute.": "Wrong code. Try again in a minute.",
  "Bonne dégustation ! Un nouveau râtelier commence.": "Enjoy! A new spoon rack begins.",
  "Dixième cuillère : votre chocolat est offert !": "Tenth spoon: your hot chocolate is on us!",
  "{n} cuillères accrochées": "{n} spoons hung up",
  "Une cuillère de plus": "One more spoon",
  "Avis de clients, un par page": "Customer reviews, one per page",
  "avis": "review",
  "{i} sur {n}": "{i} of {n}",
  "{k} étoiles sur 5": "{k} out of 5 stars",
  "Avis précédent": "Previous review",
  "Avis {i}": "Review {i}",
  "Avis suivant": "Next review",
  "Avis d’exemple de la maquette : à remplacer par une sélection de vrais avis Google.": "Sample reviews for this mock-up: to be replaced with a selection of real Google reviews.",
  "Leurs photos Instagram : touchez ou faites glisser pour passer à la suivante": "Their Instagram photos: tap or swipe to see the next one",
  "Le salon de thé : la vieille armoire vitrée et ses livres, la chaise bistrot en bois courbé, le guéridon menthe et la vaisselle ancienne, sous la suspension dorée": "The tea room: the old glass-fronted armoire with its books, the bentwood bistro chair, the mint-green pedestal table and the vintage crockery, beneath the golden pendant lamp",
  "La tasse de chocolat chaud": "The cup of hot chocolate",
  "L'armoire vitrée et ses cuillères": "The glass-fronted armoire and its spoons",
  "Le livre ouvert sur la malle": "The open book on the trunk",
  "La chaise bistrot en bois courbé": "The bentwood bistro chair",
  "Le coussin de la chaise rose": "The cushion on the pink chair",
  "La théière à fleurs": "The floral teapot",
  "La suspension": "The pendant lamp",
  "Un plat salé au choix, et sa salade composée": "A savoury dish of your choice, with a mixed salad",
  "Une boisson chaude : café, thé ou chocolat chaud": "A hot drink: coffee, tea or hot chocolate",
  "Le cookie de L’Armoire": "L’Armoire’s cookie",
  "Le beurre": "Butter",
  "Les confitures, maison pour la plupart": "Jams, mostly homemade",
  "Le miel de la Miellerie de Grattepaille": "Honey from the Miellerie de Grattepaille",
  "Le fromage blanc": "Fromage blanc",
  "Le muesli": "Muesli",
  "Les pâtes à tartiner": "Spreads",
  "Les fruits frais": "Fresh fruit",
  "Les petites gourmandises": "Little treats",
  "pile de photos": "photo stack",
  "carrousel": "carousel",
  "06 12 34 56 78": "+44 7700 900123",
  "06 …": "+44 …",
};
